name = "formcarry-rd-webhook"
type = "typescript"
main = "./dist/index.js"
compatibility_date = "2024-06-10"
account_id = "eed1dcb5bc6b2cd005ee559705499c8e"
workers_dev = true

[build]
command = "npm run build"

[vars]
RD_STATION_API_URL = "https://api.rd.services/platform/conversions"